name: bancalcaj_app
description: "Banco de alimentos de Cajamarca App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  encrypt: ^5.0.3
  excel: ^4.0.2
  flutter:
    sdk: flutter
  flutter_cors: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  intl: ^0.18.1
  mongo_dart: ^0.10.0
  mqtt_client: ^10.2.0
  path_provider: ^2.1.3
  signature: ^5.4.1
  syncfusion_flutter_pdf: ^25.1.40

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pdf/
    - assets/font/
    - assets/svg/
    - assets/excel/
