name: bancalcaj_app
description: "Banco de alimentos de Cajamarca App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  autocomplete_textfield: ^2.0.1
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  gsheets: ^0.5.0
  intl: ^0.18.1
  signature: ^5.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
