name: Build Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows --release
      - name: Create ZIP file
        run: |
          mkdir output
          powershell Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath output/flutter-windows-app.zip

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-windows-app
          path: output/flutter-windows-app.zip